=== Wasteland-Ventures-Group/WV-VTT-module/src/schemas/item/weapon.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CompendiumWeapon",
  "definitions": {
    "CompendiumWeapon": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "description": "The data base ID. It needs to be unique per compendium and should match the regular expression: `/^[a-zA-Z0-9]{16}$/`",
          "pattern": "^[a-zA-Z0-9]{16}$"
        },
        "name": {
          "type": "string",
          "description": "The name of the entry in the compendium"
        },
        "type": {
          "type": "string",
          "const": "weapon",
          "description": "The Actor or Item type name"
        },
        "data": {
          "$ref": "#/definitions/WeaponDataSourceData",
          "description": "The entry's system data"
        },
        "img": { "type": "string", "description": "The image of the entry" },
        "effects": {
          "type": "array",
          "items": {},
          "description": "Foundry Active Effects on the entry"
        },
        "flags": {
          "type": "object",
          "additionalProperties": {},
          "description": "Custom flags on the entry"
        }
      },
      "required": ["_id", "data", "effects", "flags", "img", "name", "type"],
      "additionalProperties": false
    },
    "WeaponDataSourceData": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the item in the Wasteland Wares list. This is not the name a player can give their specific instance of an item, but rather the name of the item \"prototype\"."
        },
        "description": {
          "type": "string",
          "description": "The description of the item in the Wasteland Wares list."
        },
        "notes": { "type": "string", "description": "User provided notes." },
        "rules": {
          "$ref": "#/definitions/DbRules",
          "description": "The rules of the item."
        },
        "value": {
          "type": "number",
          "description": "The value of the item in caps"
        },
        "weight": {
          "type": "number",
          "description": "The weight of the item in kg (can be floating point)"
        },
        "attacks": {
          "$ref": "#/definitions/AttacksSource",
          "description": "The attacks of the weapon"
        },
        "holdout": {
          "type": "boolean",
          "description": "Whether the weapon is a holdout weapon. By default, this is `false`."
        },
        "ranges": {
          "$ref": "#/definitions/Ranges",
          "description": "The ranges of the weapon"
        },
        "reload": {
          "$ref": "#/definitions/Reload",
          "description": "The reload stats of the weapon. By default, the weapon does not support reloading."
        },
        "skill": {
          "$ref": "#/definitions/SkillName",
          "description": "The skill associated with the weapon attacks"
        },
        "strengthRequirement": {
          "type": "number",
          "description": "The strength requirement for this weapon to be equipped"
        }
      },
      "required": [
        "attacks",
        "description",
        "name",
        "notes",
        "ranges",
        "rules",
        "skill",
        "strengthRequirement",
        "value",
        "weight"
      ],
      "additionalProperties": false,
      "description": "The Weapon Item data-source data"
    },
    "DbRules": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "array",
          "items": { "$ref": "#/definitions/RuleElementSource" },
          "description": "The source objects for the RuleElements"
        }
      },
      "required": ["sources"],
      "additionalProperties": false,
      "description": "A RuleElements DB container, that can be used in different Items."
    },
    "RuleElementSource": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "description": "Whether this rule element is enabled"
        },
        "label": {
          "type": "string",
          "description": "The label of the element"
        },
        "priority": {
          "type": "number",
          "description": "The place in the order of application, starting with lowest"
        },
        "selector": {
          "type": "string",
          "description": "The selector of the element"
        },
        "type": {
          "type": "string",
          "description": "The type identifier of the element"
        },
        "value": { "type": "number", "description": "The value of the element" }
      },
      "required": ["enabled", "label", "priority", "selector", "type", "value"],
      "additionalProperties": false,
      "description": "The RuleElement raw data layout"
    },
    "AttacksSource": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/AttackSource" },
          "description": "The source objects for the Attacks"
        }
      },
      "required": ["sources"],
      "additionalProperties": false,
      "description": "A Weapon Attacks DB container"
    },
    "AttackSource": {
      "type": "object",
      "properties": {
        "damage": {
          "type": "object",
          "properties": {
            "base": {
              "type": "number",
              "description": "The base damage amount"
            },
            "dice": {
              "type": "number",
              "description": "The number of d6 to throw for variable damage"
            },
            "diceRange": {
              "type": "boolean",
              "description": "Whether the die property is the minimum value of a die range. By default this is false."
            },
            "damageFallOff": {
              "type": "string",
              "const": "shotgun",
              "description": "The type of damage fall-off for the attack. By default the attack has no fall-off."
            }
          },
          "required": ["base", "dice"],
          "additionalProperties": false,
          "description": "The values related to the damage the weapon causes"
        },
        "rounds": {
          "type": "number",
          "description": "The amount of rounds used with the attack. By default the attack does not consume rounds."
        },
        "dtReduction": {
          "type": "number",
          "description": "The damage threshold reduction of the attack. By default the attack has no DT reduction."
        },
        "splash": {
          "description": "The splash radius. By default the attack has no splash."
        },
        "ap": {
          "type": "number",
          "description": "The amount of action points needed to attack"
        }
      },
      "required": ["damage", "ap"],
      "additionalProperties": false,
      "description": "The Attack raw data layout"
    },
    "Ranges": {
      "type": "object",
      "properties": {
        "short": {
          "$ref": "#/definitions/Range",
          "description": "The short range of the weapon"
        },
        "medium": {
          "$ref": "#/definitions/Range",
          "description": "The medium range of the weapon. By default the weapon has no medium range."
        },
        "long": {
          "$ref": "#/definitions/Range",
          "description": "The long range of the weapon. By default the weapon has no long range."
        }
      },
      "required": ["short"],
      "additionalProperties": false,
      "description": "An interface that represents the source ranges of a weapon."
    },
    "Range": {
      "type": "object",
      "properties": {
        "distance": {
          "$ref": "#/definitions/Distance",
          "description": "The maximum distance of this range in meters. It can either be a number, which represents a distance in meters, \"melee\" or a SPECIAL based range, with a base range, a multiplier and a SPECIAL name."
        },
        "modifier": {
          "type": "number",
          "description": "The skill check modifier associated with this range"
        }
      },
      "required": ["distance", "modifier"],
      "additionalProperties": false,
      "description": "An interface to represent values needed for an weapon's range"
    },
    "Distance": {
      "anyOf": [
        { "type": "number" },
        { "type": "string", "const": "melee" },
        { "$ref": "#/definitions/SpecialBasedRange" }
      ],
      "description": "A distance specifier for a weapon range."
    },
    "SpecialBasedRange": {
      "type": "object",
      "properties": {
        "base": {
          "type": "number",
          "description": "The base range of the range in meters"
        },
        "multiplier": {
          "type": "number",
          "description": "The SPECIAL multiplier"
        },
        "special": {
          "$ref": "#/definitions/SpecialName",
          "description": "The name of the SPECIAL to use"
        }
      },
      "required": ["base", "multiplier", "special"],
      "additionalProperties": false,
      "description": "A SPECIAL based range"
    },
    "SpecialName": {
      "type": "string",
      "enum": [
        "strength",
        "perception",
        "endurance",
        "charisma",
        "intelligence",
        "agility",
        "luck"
      ]
    },
    "Reload": {
      "type": "object",
      "properties": {
        "ap": {
          "type": "number",
          "description": "The amount of action points needed to reload"
        },
        "caliber": { "description": "The caliber, used by the weapon" },
        "containerType": {
          "$ref": "#/definitions/AmmoContainer",
          "description": "The ammon container type of the weapon"
        },
        "size": {
          "type": "number",
          "description": "The amount of ammo that fits into the weapon's ammo container"
        }
      },
      "required": ["ap", "caliber", "containerType", "size"],
      "additionalProperties": false,
      "description": "A type specifying the way a weapon is reloaded"
    },
    "AmmoContainer": {
      "type": "string",
      "enum": ["internal", "magazine"],
      "description": "A type for ammo containers"
    },
    "SkillName": {
      "type": "string",
      "enum": [
        "barter",
        "diplomacy",
        "explosives",
        "firearms",
        "intimidation",
        "lockpick",
        "magicalEnergyWeapons",
        "mechanics",
        "medicine",
        "melee",
        "science",
        "sleight",
        "sneak",
        "survival",
        "thaumaturgy",
        "unarmed"
      ]
    }
  }
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/yao_guai_gauntlets.json
{
  "name": "Yao Guai Gauntlets",
  "type": "weapon",
  "img": "icons/weapons/fist/claws-engraved-grey.webp",
  "data": {
    "name": "Yao Guai Gauntlets",
    "description": "Designed for hugging really, really hard.",
    "notes": "",
    "attacks": {
      "sources": {
        "Strike": {
          "damage": {
            "base": 2,
            "dice": 1,
            "diceRange": true
          },
          "ap": 5
        }
      }
    },
    "ranges": {
      "short": {
        "distance": "melee",
        "modifier": 0
      }
    },
    "holdout": true,
    "skill": "unarmed",
    "strengthRequirement": 4,
    "value": 150,
    "weight": 3.5,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000087"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/arcane_lance.json
{
  "name": "Arcane Lance",
  "type": "weapon",
  "img": "icons/weapons/polearms/spear-flared-purple.webp",
  "data": {
    "name": "Arcane Lance",
    "description": "Glowing sharp gem on a stick",
    "notes": "Can inflict Burning status on crit",
    "attacks": {
      "sources": {
        "Strike": {
          "damage": {
            "base": 3,
            "dice": 2,
            "diceRange": true
          },
          "dtReduction": 2,
          "ap": 7
        }
      }
    },
    "ranges": {
      "short": {
        "distance": 2,
        "modifier": 0
      }
    },
    "skill": "melee",
    "strengthRequirement": 7,
    "value": 700,
    "weight": 8,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000063"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/main/compendiums/item/weapon/buckscatter_m12_grandstallion.json
{
  "name": "Buckscatter M12 \"Grandstallion\"",
  "type": "weapon",
  "img": "icons/weapons/guns/gun-double-barrel.webp",
  "data": {
    "name": "Buckscatter M12 \"Grandstallion\"",
    "description": "A literal boomstick, will deliver a kick to anyone you point it towards.",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "ap": 4,
          "damage": {
            "base": 1,
            "dice": 7,
            "damageFallOff": "shotgun"
          },
          "rounds": 1
        },
        "Burst": {
          "ap": 5,
          "damage": {
            "base": 2,
            "dice": 10,
            "damageFallOff": "shotgun"
          },
          "rounds": 2
        }
      }
    },
    "ranges": {
      "short": {
        "distance": 12,
        "modifier": 0
      },
      "medium": {
        "distance": 24,
        "modifier": -10
      },
      "long": {
        "distance": 36,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 3,
      "caliber": "shotgunShell",
      "containerType": "internal",
      "size": 2
    },
    "rules": {
      "sources": []
    },
    "skill": "firearms",
    "strengthRequirement": 6,
    "value": 500,
    "weight": 3.5
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000013"
}
