=== Wasteland-Ventures-Group/WV-VTT-module/src/schemas/item/weapon.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CompendiumWeapon",
  "definitions": {
    "CompendiumWeapon": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "description": "The data base ID. It needs to be unique per compendium and should match the regular expression: `/^[a-zA-Z0-9]{16}$/`",
          "pattern": "^[a-zA-Z0-9]{16}$"
        },
        "name": {
          "type": "string",
          "description": "The name of the entry in the compendium"
        },
        "type": {
          "type": "string",
          "const": "weapon",
          "description": "The Actor or Item type name"
        },
        "data": {
          "$ref": "#/definitions/WeaponDataSourceData",
          "description": "The entry's system data"
        },
        "img": { "type": "string", "description": "The image of the entry" },
        "effects": {
          "type": "array",
          "items": {},
          "description": "Foundry Active Effects on the entry"
        },
        "flags": {
          "type": "object",
          "additionalProperties": {},
          "description": "Custom flags on the entry"
        }
      },
      "required": ["_id", "data", "effects", "flags", "img", "name", "type"],
      "additionalProperties": false
    },
    "WeaponDataSourceData": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the item in the Wasteland Wares list. This is not the name a player can give their specific instance of an item, but rather the name of the item \"prototype\"."
        },
        "description": {
          "type": "string",
          "description": "The description of the item in the Wasteland Wares list."
        },
        "notes": { "type": "string", "description": "User provided notes." },
        "rules": {
          "$ref": "#/definitions/DbRules",
          "description": "The rules of the item."
        },
        "value": {
          "type": "number",
          "description": "The value of the item in caps"
        },
        "weight": {
          "type": "number",
          "description": "The weight of the item in kg (can be floating point)"
        },
        "attacks": {
          "$ref": "#/definitions/AttacksSource",
          "description": "The attacks of the weapon"
        },
        "holdout": {
          "type": "boolean",
          "description": "Whether the weapon is a holdout weapon. By default, this is `false`."
        },
        "ranges": {
          "$ref": "#/definitions/Ranges",
          "description": "The ranges of the weapon"
        },
        "reload": {
          "$ref": "#/definitions/Reload",
          "description": "The reload stats of the weapon. By default, the weapon does not support reloading."
        },
        "skill": {
          "$ref": "#/definitions/SkillName",
          "description": "The skill associated with the weapon attacks"
        },
        "strengthRequirement": {
          "type": "number",
          "description": "The strength requirement for this weapon to be equipped"
        }
      },
      "required": [
        "attacks",
        "description",
        "name",
        "notes",
        "ranges",
        "rules",
        "skill",
        "strengthRequirement",
        "value",
        "weight"
      ],
      "additionalProperties": false,
      "description": "The Weapon Item data-source data"
    },
    "DbRules": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "array",
          "items": { "$ref": "#/definitions/RuleElementSource" },
          "description": "The source objects for the RuleElements"
        }
      },
      "required": ["sources"],
      "additionalProperties": false,
      "description": "A RuleElements DB container, that can be used in different Items."
    },
    "RuleElementSource": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "description": "Whether this rule element is enabled"
        },
        "label": {
          "type": "string",
          "description": "The label of the element"
        },
        "priority": {
          "type": "number",
          "description": "The place in the order of application, starting with lowest"
        },
        "selector": {
          "type": "string",
          "description": "The selector of the element"
        },
        "type": {
          "type": "string",
          "description": "The type identifier of the element"
        },
        "value": { "type": "number", "description": "The value of the element" }
      },
      "required": ["enabled", "label", "priority", "selector", "type", "value"],
      "additionalProperties": false,
      "description": "The RuleElement raw data layout"
    },
    "AttacksSource": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/AttackSource" },
          "description": "The source objects for the Attacks"
        }
      },
      "required": ["sources"],
      "additionalProperties": false,
      "description": "A Weapon Attacks DB container"
    },
    "AttackSource": {
      "type": "object",
      "properties": {
        "damage": {
          "type": "object",
          "properties": {
            "base": {
              "type": "number",
              "description": "The base damage amount"
            },
            "dice": {
              "type": "number",
              "description": "The number of d6 to throw for variable damage"
            },
            "diceRange": {
              "type": "boolean",
              "description": "Whether the die property is the minimum value of a die range. By default this is false."
            },
            "damageFallOff": {
              "type": "string",
              "const": "shotgun",
              "description": "The type of damage fall-off for the attack. By default the attack has no fall-off."
            }
          },
          "required": ["base", "dice"],
          "additionalProperties": false,
          "description": "The values related to the damage the weapon causes"
        },
        "rounds": {
          "type": "number",
          "description": "The amount of rounds used with the attack. By default the attack does not consume rounds."
        },
        "dtReduction": {
          "type": "number",
          "description": "The damage threshold reduction of the attack. By default the attack has no DT reduction."
        },
        "splash": {
          "description": "The splash radius. By default the attack has no splash."
        },
        "ap": {
          "type": "number",
          "description": "The amount of action points needed to attack"
        }
      },
      "required": ["damage", "ap"],
      "additionalProperties": false,
      "description": "The Attack raw data layout"
    },
    "Ranges": {
      "type": "object",
      "properties": {
        "short": {
          "$ref": "#/definitions/Range",
          "description": "The short range of the weapon"
        },
        "medium": {
          "$ref": "#/definitions/Range",
          "description": "The medium range of the weapon. By default the weapon has no medium range."
        },
        "long": {
          "$ref": "#/definitions/Range",
          "description": "The long range of the weapon. By default the weapon has no long range."
        }
      },
      "required": ["short"],
      "additionalProperties": false,
      "description": "An interface that represents the source ranges of a weapon."
    },
    "Range": {
      "type": "object",
      "properties": {
        "distance": {
          "$ref": "#/definitions/Distance",
          "description": "The maximum distance of this range in meters. It can either be a number, which represents a distance in meters, \"melee\" or a SPECIAL based range, with a base range, a multiplier and a SPECIAL name."
        },
        "modifier": {
          "type": "number",
          "description": "The skill check modifier associated with this range"
        }
      },
      "required": ["distance", "modifier"],
      "additionalProperties": false,
      "description": "An interface to represent values needed for an weapon's range"
    },
    "Distance": {
      "anyOf": [
        { "type": "number" },
        { "type": "string", "const": "melee" },
        { "$ref": "#/definitions/SpecialBasedRange" }
      ],
      "description": "A distance specifier for a weapon range."
    },
    "SpecialBasedRange": {
      "type": "object",
      "properties": {
        "base": {
          "type": "number",
          "description": "The base range of the range in meters"
        },
        "multiplier": {
          "type": "number",
          "description": "The SPECIAL multiplier"
        },
        "special": {
          "$ref": "#/definitions/SpecialName",
          "description": "The name of the SPECIAL to use"
        }
      },
      "required": ["base", "multiplier", "special"],
      "additionalProperties": false,
      "description": "A SPECIAL based range"
    },
    "SpecialName": {
      "type": "string",
      "enum": [
        "strength",
        "perception",
        "endurance",
        "charisma",
        "intelligence",
        "agility",
        "luck"
      ]
    },
    "Reload": {
      "type": "object",
      "properties": {
        "ap": {
          "type": "number",
          "description": "The amount of action points needed to reload"
        },
        "caliber": { "description": "The caliber, used by the weapon" },
        "containerType": {
          "$ref": "#/definitions/AmmoContainer",
          "description": "The ammon container type of the weapon"
        },
        "size": {
          "type": "number",
          "description": "The amount of ammo that fits into the weapon's ammo container"
        }
      },
      "required": ["ap", "caliber", "containerType", "size"],
      "additionalProperties": false,
      "description": "A type specifying the way a weapon is reloaded"
    },
    "AmmoContainer": {
      "type": "string",
      "enum": ["internal", "magazine"],
      "description": "A type for ammo containers"
    },
    "SkillName": {
      "type": "string",
      "enum": [
        "barter",
        "diplomacy",
        "explosives",
        "firearms",
        "intimidation",
        "lockpick",
        "magicalEnergyWeapons",
        "mechanics",
        "medicine",
        "melee",
        "science",
        "sleight",
        "sneak",
        "survival",
        "thaumaturgy",
        "unarmed"
      ]
    }
  }
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/if-71_epona.json
{
  "name": "IF-71 Epona",
  "type": "weapon",
  "img": "icons/svg/item-bag.svg",
  "data": {
    "name": "IF-71 Epona",
    "description": "A pistol designed for special operations use. Literal hoofcannon",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "ap": 4,
          "damage": {
            "base": 3,
            "dice": 4,
            "diceRange": false
          },
          "dtReduction": 0,
          "rounds": 1,
          "splash": "TODO"
        }
      }
    },
    "holdout": false,
    "ranges": {
      "short": {
        "distance": 20,
        "modifier": 0
      },
      "medium": {
        "distance": 40,
        "modifier": -10
      },
      "long": {
        "distance": 60,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 4,
      "caliber": "TODO",
      "containerType": "magazine",
      "size": 8
    },
    "rules": {
      "sources": []
    },
    "skill": "firearms",
    "strengthRequirement": 6,
    "value": 550,
    "weight": 1.5
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000003"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/main/compendiums/item/weapon/gauss_shotgun.json
{
  "name": "Gauss Shotgun",
  "type": "weapon",
  "img": "icons/weapons/guns/gun-blunderbuss-gold.webp",
  "data": {
    "name": "Gauss Shotgun",
    "description": "This magical energy shotgun sports only the best, most outrageously pure crystals as its Exciter, giving it a considerable boost in power.",
    "notes": "May use either Firearms or Magic Energy Weapons skill to shoot",
    "attacks": {
      "sources": {
        "Single": {
          "damage": {
            "base": 3,
            "dice": 7,
            "damageFallOff": "shotgun"
          },
          "ap": 5,
          "dtReduction": 1,
          "rounds": 1
        }
      }
    },
    "ranges": {
      "short": {
        "distance": 20,
        "modifier": 0
      },
      "medium": {
        "distance": 40,
        "modifier": -10
      },
      "long": {
        "distance": 60,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 5,
      "caliber": "energizedCrystalPack",
      "containerType": "magazine",
      "size": 5
    },
    "skill": "magicalEnergyWeapons",
    "strengthRequirement": 5,
    "value": 800,
    "weight": 3,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000038"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/main/compendiums/item/weapon/gretta_m3_smg_greaser.json
{
  "name": "Gretta M3 SMG \"Greaser\"",
  "type": "weapon",
  "img": "icons/weapons/guns/gun-brown.webp",
  "data": {
    "name": "Gretta M3 SMG \"Greaser\"",
    "description": "Popular griffin-made submachine gun. It is cheap and easy to manufacture, and its grease gun -like look is the source of its monicker",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "damage": {
            "base": 1,
            "dice": 3
          },
          "ap": 5,
          "rounds": 1
        },
        "Burst": {
          "damage": {
            "base": 2,
            "dice": 4
          },
          "ap": 6,
          "rounds": 3
        }
      }
    },
    "ranges": {
      "short": {
        "distance": 20,
        "modifier": 0
      },
      "medium": {
        "distance": 40,
        "modifier": -10
      },
      "long": {
        "distance": 60,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 4,
      "caliber": "9mm",
      "containerType": "magazine",
      "size": 30
    },
    "holdout": true,
    "skill": "firearms",
    "strengthRequirement": 3,
    "value": 200,
    "weight": 2,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000015"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/if-21_caramel.json
{
  "name": "IF-21 \"Caramel\"",
  "type": "weapon",
  "img": "icons/svg/item-bag.svg",
  "data": {
    "name": "IF-21 \"Caramel\"",
    "description": "Standard sidearm of pony officers. Proved and tested by battlefields and wastes.",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "ap": 4,
          "damage": {
            "base": 2,
            "dice": 3,
            "diceRange": false
          },
          "dtReduction": 0,
          "rounds": 1,
          "splash": "TODO"
        }
      }
    },
    "holdout": true,
    "ranges": {
      "short": {
        "distance": 20,
        "modifier": 0
      },
      "medium": {
        "distance": 40,
        "modifier": -10
      },
      "long": {
        "distance": 60,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 4,
      "caliber": "TODO",
      "containerType": "magazine",
      "size": 12
    },
    "rules": {
      "sources": []
    },
    "skill": "firearms",
    "strengthRequirement": 4,
    "value": 300,
    "weight": 1
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000002"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/lumber_axe.json
{
  "_id": "WVweapon00000055",
  "name": "Lumber Axe",
  "type": "weapon",
  "img": "icons/weapons/staves/staff-simple.webp",
  "data": {
    "name": "Lumber Axe",
    "description": "A woodcutter's basic tool, now more used for slashing through the flesh.",
    "notes": "",
    "attacks": {
      "sources": {
        "Swipe": {
          "damage": {
            "base": 2,
            "dice": 1,
            "diceRange": true
          },
          "ap": 6
        }
      }
    },
    "ranges": {
      "short": {
        "distance": "melee",
        "modifier": 0
      }
    },
    "skill": "melee",
    "strengthRequirement": 6,
    "value": 80,
    "weight": 5,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {}
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/gretta_m9.json
{
  "name": "Gretta M9",
  "type": "weapon",
  "img": "icons/weapons/guns/gun-pistol-brown.webp",
  "data": {
    "name": "Gretta M9",
    "description": "Standard firearm of griffin mercenaries, especially Talon Mercs. Reliable and cheap",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "ap": 4,
          "damage": {
            "base": 1,
            "dice": 2,
            "diceRange": false
          },
          "dtReduction": 0,
          "rounds": 1,
          "splash": "TODO"
        }
      }
    },
    "holdout": true,
    "ranges": {
      "short": {
        "distance": 20,
        "modifier": 0
      },
      "medium": {
        "distance": 40,
        "modifier": -10
      },
      "long": {
        "distance": 60,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 4,
      "caliber": "TODO",
      "containerType": "magazine",
      "size": 12
    },
    "rules": {
      "sources": []
    },
    "skill": "firearms",
    "strengthRequirement": 2,
    "value": 100,
    "weight": 1
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000001"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/compendiums/item/weapon/handk_mgat-39_mini_gun.json
{
  "name": "H&K MGat-39 \"Mini Gun\"",
  "type": "weapon",
  "img": "icons/weapons/guns/rifle-brown.webp",
  "data": {
    "name": "H&K MGat-39 \"Mini Gun\"",
    "description": "A ferocious, but reliable machine gun developed by a late-war competitor to Ironshod.",
    "notes": "Point blank accuracy modifier -10",
    "attacks": {
      "sources": {
        "Burst": {
          "damage": {
            "base": 3,
            "dice": 9
          },
          "ap": 9,
          "rounds": 10
        }
      }
    },
    "reload": {
      "ap": 11,
      "caliber": "TODO",
      "containerType": "magazine",
      "size": 240
    },
    "ranges": {
      "short": {
        "distance": 30,
        "modifier": 0
      },
      "medium": {
        "distance": 60,
        "modifier": -10
      },
      "long": {
        "distance": 90,
        "modifier": -20
      }
    },
    "skill": "firearms",
    "strengthRequirement": 9,
    "value": 750,
    "weight": 15,
    "rules": {
      "sources": []
    }
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000020"
}

=== Wasteland-Ventures-Group/WV-VTT-module/src/main/compendiums/item/weapon/buckscatter_m9_mole_whacker.json
{
  "name": "Buckscatter M9 \"Mole Whacker\"",
  "type": "weapon",
  "img": "icons/weapons/guns/gun-double-barrel.webp",
  "data": {
    "name": "Buckscatter M9 \"Mole Whacker\"",
    "description": "A lever-action shotgun, popular in the pre-War and Wasteland Farms. \"Sure, there are newer designs, but you canâ€™t flip cock them and flip cocking makes a badass.\"",
    "notes": "",
    "attacks": {
      "sources": {
        "Single": {
          "ap": 5,
          "damage": {
            "base": 1,
            "dice": 7,
            "damageFallOff": "shotgun"
          },
          "rounds": 1
        }
      }
    },
    "ranges": {
      "short": {
        "distance": 10,
        "modifier": 0
      },
      "medium": {
        "distance": 20,
        "modifier": -10
      },
      "long": {
        "distance": 30,
        "modifier": -20
      }
    },
    "reload": {
      "ap": 2,
      "caliber": "TODO",
      "containerType": "internal",
      "size": 5
    },
    "rules": {
      "sources": []
    },
    "skill": "firearms",
    "strengthRequirement": 6,
    "value": 225,
    "weight": 1.5
  },
  "effects": [],
  "flags": {},
  "_id": "WVweapon00000012"
}
